### ISSUE TITLE
Cannot load wasm file in node v18 when using esm

### ISSUE THREAD

**Issue by RebeccaStevens** [lovasoa/highs-js#22]
This is working with node v17 but something seems to have changed in node v18

Basic setup:

| package                                | version |
| -------------------------------------- | ------- |
| `highs`                                | `0.7.2` |
| `node`                                 | `18.2.0` |

Code:

```js
import highsLoader from "highs";

const highs = await highsLoader();
return highs.solve("...");
```

Error:

```sh
TypeError: Failed to parse URL from /path/to/project/node_modules/highs/build/highs.wasm
    at new Request (node:internal/deps/undici/undici:4813:19)
    at Agent.fetch2 (node:internal/deps/undici/undici:5539:29)
    ... 7 lines matching cause stack trace ...
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at __node_internal_captureLargerStackTrace (node:internal/errors:466:5)
      at new NodeError (node:internal/errors:377:5)
      at URL.onParseError (node:internal/url:563:9)
      at new URL (node:internal/url:643:5)
      at new Request (node:internal/deps/undici/undici:4811:25)
      at Agent.fetch2 (node:internal/deps/undici/undici:5539:29)
      at Object.fetch (node:internal/deps/undici/undici:6370:20)
      at fetch (node:internal/bootstrap/pre_execution:196:25)
      at /path/to/project/node_modules/highs/build/highs.js:157:254
      at /path/to/project/node_modules/highs/build/highs.js:157:511
      at /path/to/project/node_modules/highs/build/highs.js:158:9
      at <anonymous> (/path/to/project/src/solver/lp/index.mts:12:22)
      at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Promise.all (index 0)
      at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
      at async loadESM (node:internal/process/esm_loader:85:5)
      at async handleMainPromise (node:internal/modules/run_main:61:12) {
    input: '/path/to/project/node_modules/highs/build/highs.wasm',
    code: 'ERR_INVALID_URL'
  }
}

Node.js v18.2.0
```

I think the path to the wasm file should be prefixed with `file://` but that doesn't fix everything as I then get:

```sh
(node:17381) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Generating LP
Caching LP
RuntimeError: Aborted(Error: ENOENT: no such file or directory, open 'file:/path/to/project/node_modules/highs/build/highs.wasm'). Build with -s ASSERTIONS=1 for more info.
    at B (/path/to/project/node_modules/highs/build/highs.js:21:235)
    at Ha (/path/to/project/node_modules/highs/build/highs.js:22:176)
    at /path/to/project/node_modules/highs/build/highs.js:23:453
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.2.0
```

Though I don't understand why this issue happens as the file definitely does exists.

**Comment by lovasoa** [comment]
No, you must serve the wasm file from an HTTP server, and put the URL of the file in the highs.js settings.

```
const highs_settings = {
  // In node, locateFile is not needed
  // In the browser, point locateFile to the URL of the wasm file (see below)
  locateFile: (file) => PUT YOUR URL HERE
};
```

**Comment by RebeccaStevens** [comment]
> In node, locateFile is not needed

I'm using node and it gives the error above.
